#!/bin/sh

BASE_SANDBOX_WORK_DIR="${PWD}/sandbox"
BASE_ISO_DIR="${BASE_SANDBOX_WORK_DIR}/iso"
BASE_VM_DIR="${BASE_SANDBOX_WORK_DIR}/vm"

BASE_VM_VERSION=3.21
BASE_VM_ARCHITECTURE=x86_64
BASE_VM_NAME="alpine-standard-${BASE_VM_VERSION}.3-${BASE_VM_ARCHITECTURE}"
BASE_VM_PATH="${BASE_VM_DIR}/${BASE_VM_NAME}.qcow2"
BASE_VM_RAM_SIZE="2G"
BASE_VM_DRIVE_SIZE="16G"
BASE_VM_DRIVE_TYPE="qcow2"

BASE_HASH_ALGORITHM="sha256"

BASE_ISO_URL="https://dl-cdn.alpinelinux.org/alpine/v${BASE_VM_VERSION}/releases/${BASE_VM_ARCHITECTURE}/${BASE_VM_NAME}.iso"
BASE_ISO_HASH_NAME="${BASE_ISO_NAME}.${BASE_HASH_ALGORITHM}"
BASE_ISO_PATH="${BASE_ISO_DIR}/${BASE_VM_NAME}.iso"
BASE_ISO_HASH_PATH="${BASE_ISO_DIR}/${BASE_ISO_HASH_NAME}"
BASE_ISO_IMAGE_HASH_URL="${BASE_ISO_URL}.${BASE_HASH_ALGORITHM}"

qemu-system-x86_64 -m "${BASE_VM_MEMORY_SIZE}" -hda "${BASE_VM_PATH}" -cdrom "${BASE_ISO_PATH}" -kernel "$BASE_ISO_PATH" -append "alpine autoinstall"